yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow', views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/', LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/', LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset/', PasswordResetView.as_view(
            template_name='users/password_reset.html'), name='password_reset'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'core.views.permission_denied'
handler403csrf = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group (models.Model):
    title = models.CharField('Название', max_length=200)
    slug = models.SlugField('Адрес URL', unique=True)
    description = models.TextField('Описание сообщества')

    class Meta:
        verbose_name = ('Сообщество')
        verbose_name_plural = ('Сообщества')

    def __str__(self):
        return f'{self.title}'


class Post (models.Model):
    text = models.TextField('Текст поста')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        verbose_name='Автор поста',
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        verbose_name='Название сообщества',
        blank=True,
        on_delete=models.SET_NULL,
        null=True,
        related_name='posts'
    )
    image = models.ImageField(
        'Изображение',
        upload_to='posts/',
        blank=True,
    )

    class Meta:
        verbose_name = ('Запись')
        verbose_name_plural = ('Записи')
        ordering = ('-pub_date',)

    def __str__(self):
        return f'{self.text[:15]}'


class Comment (models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name='Комментарий к посту',
        blank=False,
        on_delete=models.CASCADE,
        null=True,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор комментария',
        blank=False,
        on_delete=models.CASCADE,
        null=True,
        related_name='comments'
    )
    text = models.TextField('Текст комментария')
    created = models.DateTimeField('Дата публикации комментария',
                                   auto_now_add=True)

    class Meta:
        verbose_name = ('Комментарий')
        verbose_name_plural = ('Комментарии')


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='Подписчик',
        blank=False,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор постов',
        blank=False,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='user_author')
        ]
        verbose_name = ('Подписки')
        verbose_name_plural = ('Подписки')

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm (forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Название группы',
            'image': 'Изображение к посту'
        }
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост.',
            'image': 'Изображение к посту'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['group'].empty_label = (
            'Выберите группу, если желаете'
        )
        self.fields['text'].widget.attrs['placeholder'] = (
            'Введите какой-нибудь текст, пожалуйста.'
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Текст комментария'}
        help_text = {'text': 'Введите комментарий'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['placeholder'] = (
            'В данное поле, можно написать комментарий.'
        )

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import paginator


@cache_page(20)
def index(request):
    posts_list = Post.objects.select_related('author').all()
    page_obj = paginator(posts_list, request)
    template = 'posts/index.html'
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts_list = group.posts.all()
    page_obj = paginator(posts_list, request)
    template = 'posts/group_list.html'
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts_list = author.posts.all()
    page_obj = paginator(posts_list, request)
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user, author=author).exists()
    )
    template = 'posts/profile.html'
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post.objects.select_related(
        'author', 'group'), id=post_id)
    form_comment = CommentForm(request.POST or None)
    comments = post.comments.all()
    template = 'posts/post_detail.html'
    context = {
        'post': post,
        'form': form_comment,
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()
        return redirect('posts:profile', username=post.author)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        files=request.FILES or None,
        instance=post,
    )
    author = post.author
    template = 'posts/create_post.html'
    context = {
        'form': form,
        'post': post,
        'is_edit': True,
    }
    if author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    if request.method != 'POST':
        return render(request, template, context)
    form = PostForm(request.POST, instance=post, files=request.FILES or None)
    if not form.is_valid():
        return render(request, template, {'form': form})
    post = form.save(commit=False)
    form.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator(posts_list, request)
    template = 'posts/follow.html'
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = User.objects.get(username=username)
    if request.user == author:
        return redirect('posts:profile', username=username)
    Follow.objects.get_or_create(author=author, user=request.user)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = User.objects.get(username=username)
    Follow.objects.get(author=author.id, user=request.user).delete()
    return redirect('posts:profile', username=username)

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>  © {{ year }} Copyright <span style="color:red">Ya</span>tube
  </p>
</footer>

yatube/templates/includes/form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/forms.html
{% load user_filters %}
{% for field in form %}
  <div class="form-group row my-3"
       {% if field.field.required %} aria-required="true" {% else %} aria-required="false" {% endif %}>
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
      {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
    </label>
    <div>
      {{ field|addclass:'form-control' }}
      {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
      {% endif %}
    </div>
  </div>
{% endfor %}

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}"
             width="30"
             height="30"
             class="d-inline-block align-top"
             alt="">
        <span style="color:red">Ya</span>tube
    </a>
    <ul class="nav nav-pills">
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:author' %} active {% endif %}"
           href="{% url 'about:author' %}">Об авторе</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:tech' %} active {% endif %}"
           href="{% url 'about:tech' %}">Технологии</a>
      </li>
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'posts:post_create' %} active {% endif %}"
             href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'users:password_reset' %} active {% endif %}" 
             href="{% url 'users:password_reset' %}">Изменить пароль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li class="nav-item navbar-text">
          Пользователь:
          <a href="{% url 'posts:profile' user.username %}">{{ user.username }}</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'users:login' %} active {% endif %}"
             href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'users:signup' %} active {% endif %}"
             href="{% url 'users:signup' %}">Регистрация</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endwith %}

yatube/templates/includes/pages_html.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">Первая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/includes/posts.html
{% load thumbnail%}
<article>
  <ul>
    {% if not show_author %}
      <li>
        Автор:
        <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
      </li>
    {% endif %}
    <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
  </ul>
  {% thumbnail post.image "960x339" crop="" as im %}
      <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" >
  {% endthumbnail %}
  <p>
    {{ post.text|linebreaksbr }}
  </p>
  <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
</article>
{% if post.group and show_link %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
{% endif %}

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
  {% with request.resolver_match.view_name as view_name %}
    <div class="row my-3">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'posts:index' %} active {% endif %}"
             href="{% url 'posts:index' %}">Все авторы</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'posts:follow_index' %} active {% endif %}"
             href="{% url 'posts:follow_index' %}">Избранные авторы</a>
        </li>
      </ul>
    </div>
  {% endwith %}
{% endif %}